#!/usr/bin/env python

import os

# Start the roscore
os.system('roscore')

# Set the TURTLEBOT3_MODEL environment variable
os.environ['TURTLEBOT3_MODEL'] = 'waffle_pi'

# Launch the turtlebot3 world in Gazebo
os.system('roslaunch turtlebot3_gazebo turtlebot3_world.launch')

# Launch the SLAM node for mapping
os.system('roslaunch turtlebot3_slam turtlebot3_slam.launch slam_methods:=gmapping')

# Launch the turtlebot3 simulation in Gazebo
os.system('roslaunch turtlebot3_gazebo turtlebot3_simulation.launch')

# Save the map generated by SLAM
os.system('rosrun map_server map_saver -f ~/map')

# Terminate all running ROS nodes
os.system('rosnode kill -a')

# Set the TURTLEBOT3_MODEL environment variable again
os.environ['TURTLEBOT3_MODEL'] = 'waffle_pi'

# Launch the turtlebot3 world in Gazebo
os.system('roslaunch turtlebot3_gazebo turtlebot3_world.launch')

# Launch the navigation node and load the saved map
os.system('roslaunch turtlebot3_navigation turtlebot3_navigation.launch map_file:=$HOME/map.yaml')
